swipe:
  3:
    left: 
      command: 'qdbus org.kde.KWin /KWin nextDesktop'
    right: 
      command: 'qdbus org.kde.KWin /KWin previousDesktop'
    up: 
      command: 'qdbus org.kde.kglobalaccel /component/lattedock invokeShortcut "activate widget 4"'
    down: 
      command: 'qdbus org.kde.kglobalaccel /component/lattedock invokeShortcut "activate widget 4"'
threshold:
  swipe: 0.4
  pinch: 0.2
interval:
  swipe: 0.3
  pinch: 0.1
