swipe:
  3:
    left: 
      command: 'qdbus org.kde.KWin /KWin nextDesktop'
    right: 
      command: 'qdbus org.kde.KWin /KWin previousDesktop'
    up: 
      command: 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Expose"'
    down: 
      command: 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "ExposeAll"'
threshold:
  swipe: 0.6
  pinch: 0.2
interval:
  swipe: 0.3
  pinch: 0.1
